export const ENDPOINTS = {
  HISTORIAL: FLOW_HISTORIAL_REGISTROS,
  
  DETALLE_REGISTRO: FLOW_REGISTROS_DETALLE,
  
  CARGAR_DATOS_EDICION: FLOW_MODIFICAR_REGISTRO_EXISTENTE,
  
  ANALISIS_PROTECCION: FLOW_RELLENAR_AJUSTES_RECOMENDADOS,
  
  ENVIAR_FOTOS: FLOW_ENVIAR_FOTOS_FORMULARIO_PP,
  
  ENVIAR_FORMULARIO_PP: FLOW_GENERAR_PLANTILLA_PP,
  
  ENVIAR_FORMULARIO_PS: FLOW_GENERAR_PLANTILLA_PS,
  
  ENVIAR_FORMULARIO_CA: FLOW_GENERAR_PLANTILLA_CA
};

