name: Deploy App
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Reemplazo Seguro (Rastreo Multicarpeta)
        shell: node {0}
        run: |
          const fs = require('fs');
          const path = require('path');

          const targetFile = path.join('js', 'config', 'endpoints.js');

          const replacements = {
            'FLOW_HISTORIAL_REGISTROS': process.env.URL_HISTORIAL,
            'FLOW_GENERAR_PLANTILLA_PP': process.env.URL_PP,
            'FLOW_GENERAR_PLANTILLA_PS': process.env.URL_PS,
            'FLOW_GENERAR_PLANTILLA_CA': process.env.URL_CA,
            'FLOW_REGISTROS_DETALLE': process.env.URL_DETALLE,
            'FLOW_MODIFICAR_REGISTRO_EXISTENTE': process.env.URL_MODIFICA,
            'FLOW_RELLENAR_AJUSTES_RECOMENDADOS': process.env.URL_AJUSTES,
            'FLOW_ENVIAR_FOTOS_FORMULARIO_PP': process.env.URL_FOTOS
          };

          if (fs.existsSync(targetFile)) {
            let content = fs.readFileSync(targetFile, 'utf8');
            let modified = false;

            Object.entries(replacements).forEach(([key, value]) => {
              if (value && content.includes(key)) {
                // Limpieza de comillas y reemplazo
                const cleanUrl = value.replace(/['"`]/g, '');
                content = content.split(key).join("'" + cleanUrl + "'");
                modified = true;
                console.log(`✅ REEMPLAZADO ${key} en: ${targetFile}`);
              }
            });

               if (modified) {
              fs.writeFileSync(targetFile, content);
              console.log('--- Archivo endpoints.js actualizado con éxito ---');
            } else {
              console.log('⚠️ No se encontraron claves para reemplazar en endpoints.js');
            }
          } else {
            console.error(`❌ Error: No se encontró el archivo en ${targetFile}`);
            process.exit(1);
          }
        env:
          URL_HISTORIAL: ${{ secrets.FLOW_HISTORIAL_REGISTROS }}
          URL_PP: ${{ secrets.FLOW_GENERAR_PLANTILLA_PP }}
          URL_PS: ${{ secrets.FLOW_GENERAR_PLANTILLA_PS }}
          URL_CA: ${{ secrets.FLOW_GENERAR_PLANTILLA_CA }}
          URL_DETALLE: ${{ secrets.FLOW_REGISTROS_DETALLE }}
          URL_MODIFICA: ${{ secrets.FLOW_MODIFICAR_REGISTRO_EXISTENTE }}
          URL_AJUSTES: ${{ secrets.FLOW_RELLENAR_AJUSTES_RECOMENDADOS }}
          URL_FOTOS: ${{ secrets.FLOW_ENVIAR_FOTOS_FORMULARIO_PP }}

      - name: Deploy a GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
          clean: true
